// Code generated by schema tool; DO NOT EDIT.

#![allow(dead_code)]
#![allow(unused_mut)]

use wasmlib::*;

pub struct SwapEvents {
}

impl SwapEvents {

	pub fn price_log(&self,
        block_num: u64,
        price: u64,
    ) {
		let mut enc = EventEncoder::new("swap.priceLog");
		uint64_encode(&mut enc, block_num);
		uint64_encode(&mut enc, price);
		EventEncoder::emit(&enc);
	}
}
