// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

#![allow(dead_code)]

use wasmlib::*;

use crate::*;

pub struct UpdatePriceCall<'a> {
    pub func:    ScFunc<'a>,
    pub results: ImmutableUpdatePriceResults,
}

pub struct ScFuncs {
}

impl ScFuncs {
    pub fn update_price(ctx: &impl ScFuncCallContext) -> UpdatePriceCall {
        let mut f = UpdatePriceCall {
            func:    ScFunc::new(ctx, HSC_NAME, HFUNC_UPDATE_PRICE),
            results: ImmutableUpdatePriceResults { proxy: Proxy::nil() },
        };
        ScFunc::link_results(&mut f.results.proxy, &f.func);
        f
    }
}
