// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

#![allow(dead_code)]
#![allow(unused_mut)]

use wasmlib::*;

pub struct recorderEvents {
}

impl recorderEvents {

	pub fn price_history(&self,
        price: u64,
    ) {
		let mut evt = EventEncoder::new("recorder.priceHistory");
		evt.encode(&uint64_to_string(price));
		evt.emit();
	}
}
