// Code generated by schema tool; DO NOT EDIT.

package swap

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"

type SetPriceCall struct {
	Func    *wasmlib.ScFunc
	Results ImmutableSetPriceResults
}

type GetPriceCall struct {
	Func    *wasmlib.ScView
	Results ImmutableGetPriceResults
}

type Funcs struct{}

var ScFuncs Funcs

func (sc Funcs) SetPrice(ctx wasmlib.ScFuncClientContext) *SetPriceCall {
	f := &SetPriceCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncSetPrice)}
	wasmlib.NewCallResultsProxy(&f.Func.ScView, &f.Results.Proxy)
	return f
}

func (sc Funcs) GetPrice(ctx wasmlib.ScViewClientContext) *GetPriceCall {
	f := &GetPriceCall{Func: wasmlib.NewScView(ctx, HScName, HViewGetPrice)}
	wasmlib.NewCallResultsProxy(f.Func, &f.Results.Proxy)
	return f
}
