// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

package swap

import (
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"
)

type SwapEvents struct{}

func (e SwapEvents) PriceLog(
	blockNum uint64,
	price uint64,
) {
	evt := wasmlib.NewEventEncoder("swap.priceLog")
	evt.Encode(wasmtypes.Uint64ToString(blockNum))
	evt.Encode(wasmtypes.Uint64ToString(price))
	evt.Emit()
}
