// Code generated by schema tool; DO NOT EDIT.

package swap

import (
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"
)

type SwapEvents struct{}

func (e SwapEvents) PriceLog(
	blockNum uint64,
	price uint64,
) {
	enc := wasmlib.NewEventEncoder("swap.priceLog")
	wasmtypes.Uint64Encode(enc, blockNum)
	wasmtypes.Uint64Encode(enc, price)
	wasmlib.EventEmit(enc)
}
