// Code generated by schema tool; DO NOT EDIT.

package swap

import (
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"
)

type ImmutableSwapState struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableSwapState() ImmutableSwapState {
	return ImmutableSwapState{Proxy: wasmlib.NewStateProxy()}
}

func (s ImmutableSwapState) LatestPrice() wasmtypes.ScImmutableUint64 {
	return wasmtypes.NewScImmutableUint64(s.Proxy.Root(StateLatestPrice))
}

type MutableSwapState struct {
	Proxy wasmtypes.Proxy
}

func NewMutableSwapState() MutableSwapState {
	return MutableSwapState{Proxy: wasmlib.NewStateProxy()}
}

func (s MutableSwapState) AsImmutable() ImmutableSwapState {
	return ImmutableSwapState(s)
}

func (s MutableSwapState) LatestPrice() wasmtypes.ScMutableUint64 {
	return wasmtypes.NewScMutableUint64(s.Proxy.Root(StateLatestPrice))
}
