// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

#![allow(dead_code)]

use wasmlib::*;

pub const SC_NAME        : &str = "recorder";
pub const SC_DESCRIPTION : &str = "An example recorder contract";
pub const HSC_NAME       : ScHname = ScHname(0xc8783c3c);

pub const FUNC_UPDATE_PRICE : &str = "updatePrice";

pub const HFUNC_UPDATE_PRICE : ScHname = ScHname(0xd6847598);
