// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

#![allow(dead_code)]

use wasmlib::*;

use crate::*;

pub struct CallForPriceCall<'a> {
    pub func: ScFunc<'a>,
}

pub struct ScFuncs {
}

impl ScFuncs {
    pub fn call_for_price(ctx: &impl ScFuncCallContext) -> CallForPriceCall {
        CallForPriceCall {
            func: ScFunc::new(ctx, HSC_NAME, HFUNC_CALL_FOR_PRICE),
        }
    }
}
