// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

#![allow(dead_code)]
#![allow(unused_imports)]

use wasmlib::*;

use crate::*;

#[derive(Clone)]
pub struct ImmutableswapState {
    pub(crate) proxy: Proxy,
}

impl ImmutableswapState {
    pub fn new() -> ImmutableswapState {
        ImmutableswapState {
            proxy: state_proxy(),
        }
    }

    pub fn latest_price(&self) -> ScImmutableUint64 {
        ScImmutableUint64::new(self.proxy.root(STATE_LATEST_PRICE))
    }
}

#[derive(Clone)]
pub struct MutableswapState {
    pub(crate) proxy: Proxy,
}

impl MutableswapState {
    pub fn new() -> MutableswapState {
        MutableswapState {
            proxy: state_proxy(),
        }
    }
    pub fn as_immutable(&self) -> ImmutableswapState {
        ImmutableswapState { proxy: self.proxy.root("") }
    }

    pub fn latest_price(&self) -> ScMutableUint64 {
        ScMutableUint64::new(self.proxy.root(STATE_LATEST_PRICE))
    }
}
