// Code generated by schema tool; DO NOT EDIT.

//go:build wasm
// +build wasm

package main

import (
	"github.com/howjmay/wasp-contract-example/contracts/swap/go/swapimpl"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmvmhost/go/wasmvmhost"
)

func main() {
}

func init() {
	wasmvmhost.ConnectWasmHost()
}

//export on_call
func onCall(index int32) {
	swapimpl.OnDispatch(index)
}

//export on_load
func onLoad() {
	swapimpl.OnDispatch(-1)
}
