// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

#![allow(dead_code)]
#![allow(unused_imports)]

use wasmlib::*;
use recorder::*;
use crate::*;

const EXPORT_MAP: ScExportMap = ScExportMap {
    names: &[
        FUNC_UPDATE_PRICE,
    ],
    funcs: &[
        func_update_price_thunk,
    ],
    views: &[
    ],
};

pub fn on_dispatch(index: i32) {
    EXPORT_MAP.dispatch(index);
}

pub struct UpdatePriceContext {
    pub events:  recorderEvents,
    pub results: MutableUpdatePriceResults,
}

fn func_update_price_thunk(ctx: &ScFuncContext) {
    ctx.log("recorder.funcUpdatePrice");
    let f = UpdatePriceContext {
        events:  recorderEvents {},
        results: MutableUpdatePriceResults::new(),
    };
    func_update_price(ctx, &f);
    ctx.results(&f.results.proxy);
    ctx.log("recorder.funcUpdatePrice ok");
}
