// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

package recorder

import (
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"
)

type RecorderEvents struct{}

func (e RecorderEvents) PriceHistory(
	price uint64,
) {
	evt := wasmlib.NewEventEncoder("recorder.priceHistory")
	evt.Encode(wasmtypes.Uint64ToString(price))
	evt.Emit()
}
