// Code generated by schema tool; DO NOT EDIT.

package recorder

import (
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"
)

type RecorderEvents struct{}

func (e RecorderEvents) PriceHistory(
	price uint64,
) {
	enc := wasmlib.NewEventEncoder("recorder.priceHistory")
	wasmtypes.Uint64Encode(enc, price)
	wasmlib.EventEmit(enc)
}
