name: Recorder
description: An example recorder contract
events:
  priceHistory:
    price: Uint64

funcs:
  updatePrice:
    results:
      success: Bool
views:
  getPrice:
    results:
      price: Uint64
